osx_image: xcode11.2
language: swift

before_install:
  - gem install cocoapods
  - carthage bootstrap --platform ios

install:
  - gem install xcpretty

script:
  - rake build:ios DESTINATION='OS=11.1,name=iPhone X'
  - rake build:ios DESTINATION='platform=iOS Simulator,name=iPhone 8'
  - pod lib lint --quick
