language: objective-c
osx_image: xcode8

before_install:
  - gem install cocoapods
  - carthage bootstrap --platform ios

install:
  - gem install xcpretty --no-rdoc --no-ri --no-document --quiet

script:
  - rake build:ios DESTINATION='OS=9.3,name=iPhone 6s'
  - rake build:ios DESTINATION='platform=iOS Simulator,name=iPhone 7 Plus'
  - pod lib lint --quick
